# Source: nack
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: argo-poker
  namespace: nats
  annotations:
    noa.re/deploy-id: ab75e836c6f5175f
spec:
  streamName: github-events
  durableName: argo-poker
  filterSubjects: idcat.github.events.push.portswigger-cloud.manifests
  ackPolicy: explicit
  deliveryPolicy: last
