# Source: nack
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: argo-poker
  namespace: nats
  annotations:
    noa.re/deploy-id: 1b02578a96ff4ecc
spec:
  streamName: github-events
  durableName: argo-poker
  filterSubjects:
  - idcat.github.events.push.nresare.berries-manifests
  ackPolicy: explicit
  deliverPolicy: last
  account: app
