# Source: nack
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jetstream-controller
  namespace: nats
  labels:
    app: nack
    chart: nack-0.34.1_noa.1
  annotations:
    nats.io/allowed-pub-subjects: $JS.ACK.>,$JS.API.>
    nats.io/allowed-sub-subjects: $JS.API.>
    noa.re/deploy-id: b6e8423573e89147
