# Source: nack
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jetstream-controller
  namespace: nats
  labels:
    app: nack
    chart: nack-0.34.0_noa
  annotations:
    noa.re/deploy-id: d855a890c83e72cb
