# Source: dm.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: dm-noa-re-config
  namespace: digital-membership
  annotations:
    noa.re/deploy-id: ba7b3f0f778dc3cf
data:
  digital-membership.toml: |
    # Example configuration for digital-membership.
    #
    # The service reads /config/digital-membership.toml by default; pass
    # --config-file to point it somewhere else.

    bind_address = "0.0.0.0:8080"

    [[issuer]]
    id = "choir"
    description = "Example Choral Society"
    signing_key_path = "/keys/choir.key"
    name_model = "/uk-0.1.1.ncmp.xz"
    flags = ["Sheet music group", "Party planners"]

    [[issuer]]
    id = "fairer"
    # description = "Make Southwark fairer action group"
    signing_key_path = "/keys/fairer.key"
    name_model = "/uk-0.1.1.ncmp.xz"
