# Source: dm.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-noa-re
  labels:
    app: dm-noa-re
  namespace: digital-membership
  annotations:
    noa.re/deploy-id: 6e65001cb2fb206e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm-noa-re
  template:
    metadata:
      labels:
        app: dm-noa-re
      annotations:
        checksum/config: b8252936169d44585f364b25c5dd2680db6552597f46425bbc206253cbe009f2
    spec:
      containers:
      - name: dm-noa-re
        image: repo.noa.re/digital-membership:0.1.0-b9a936e9
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: dm-noa-re-config
          mountPath: /config
        - name: keys
          mountPath: /keys
      volumes:
      - name: dm-noa-re-config
        configMap:
          name: dm-noa-re-config
      - name: keys
        secret:
          secretName: keys
