# Source: dm.noa.re
apiVersion: v1
kind: Service
metadata:
  name: dm-noa-re
  namespace: digital-membership
  annotations:
    noa.re/deploy-id: 709741ea00f94274
spec:
  selector:
    app: dm-noa-re
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
