# Source: loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-runtime
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.7
  annotations:
    noa.re/deploy-id: ef43e148cbc7a5e1
data:
  runtime-config.yaml: |
    {}
