# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-memcached
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.3
    app.kubernetes.io/component: memcached
automountServiceAccountToken: false
