# Source: repo.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-noa-re-config
  namespace: reposnake
data:
  reposnake.toml: |
    bind_address = "0.0.0.0:8080"
    storage_directory = "/data"
    max_upload_bytes = 104857600

    [authentication]
    audience = "repo.noa.re"
    issuer = "https://kubernetes.default.svc"

    [[publisher]]
    name = "ci"
    projects = ["*"]

    [publisher.required_claims]
    sub = "system:serviceaccount:default:default"
