# Source: repo.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-noa-re-config
  namespace: reposnake
data:
  reposnake.toml: |
    bind_address = "0.0.0.0:8080"
    max_upload_bytes = 104857600

    [[identity-provider]]
    name = "kubernetes"
    audience = "repo.noa.re"
    issuer = "https://k8s.noa.re"


    [[identity-provider]]
    name = "buildkite"
    audience = "repo.noa.re"
    issuer = "https://agent.buildkite.com"

    [[publisher]]
    name = "ci"
    projects = ["*"]
    required_claims = {organization_slug="nresare"}
    identity-provider = "buildkite"

    [[publisher]]
    name = "manual"
    projects = ["*"]
    required_claims = {sub="system:serviceaccount:default:default"}
    identity-provider = "kubernetes"

    [object-store]
    backend = "S3"
    bucket = "repo-noa-re"
    directory = "/data"

    [persistence]
    uri = "ws://surrealdb.surrealdb:8000"

    [persistence.idmouse]
    url = "http://idmouse.idmouse.svc/token/reposnake"
    token_path = "/var/run/secrets/tokens/idmouse"
