# Source: repo.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-noa-re
  labels:
    app: repo-noa-re
  namespace: reposnake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-noa-re
  template:
    metadata:
      labels:
        app: repo-noa-re
    spec:
      containers:
      - name: repo-noa-re
        image: nresare/reposnake:latest
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: repo-noa-re-data
      initContainers:
      - name: fix-data-permissions
        image: alpine:3.23.4
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - mkdir -p /data && chown -R 65532:65532 /data
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /data
