# Source: repo.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-noa-re
  labels:
    app: repo-noa-re
  namespace: reposnake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repo-noa-re
  template:
    metadata:
      labels:
        app: repo-noa-re
      annotations:
        checksum/config: d3bc992ef03b06dcad8cad7a72ab47e458b482621550b280adae8df0e4dc9924
    spec:
      containers:
      - name: repo-noa-re
        image: nresare/reposnake:0.1.7
        args:
        - -c
        - /config/reposnake.toml
        env:
        - name: AWS_REGION
          value: eu-west-2
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::190019502607:role/repo-noa-re
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/tokens/sts.amazonaws.com
        volumeMounts:
        - name: repo-noa-re-config
          mountPath: /config
        - name: emptydir-var-tmp
          mountPath: /var/tmp
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: repo-noa-re-config
        configMap:
          name: repo-noa-re-config
      - name: emptydir-var-tmp
        emptyDir: {}
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: idmouse
              expirationSeconds: 3600
              audience: idmouse
          - serviceAccountToken:
              path: sts.amazonaws.com
              expirationSeconds: 3600
              audience: sts.amazonaws.com
      initContainers:
      - name: fix-emptydir-var-tmp-permissions
        image: alpine:3.23.4
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - mkdir -p /var/tmp && chown -R 65532:65532 /var/tmp
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: emptydir-var-tmp
          mountPath: /var/tmp
