# Source: alloy
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy
  annotations:
    noa.re/deploy-id: 963c9a0b76ac41ee
data:
  alloy.cfg: |
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-distributor.mimir.svc:8080/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "anonymous",
        }
      }
    }

    prometheus.scrape "static_hosts" {
      targets = [
        {
          __address__ = "hallon:9100",
          instance    = "host1",
        },
        {
          __address__ = "smultron:9100",
          instance    = "smultron",
        },
        {
          __address__ = "lingon:9100",
          instance    = "lingon",
        },
        {
          __address__ = "hjortron:9100",
          instance    = "hjortron",
        },
        {
          __address__ = "havtorn:9100",
          instance    = "havtorn",
        },
        {
          __address__ = "nadia:9100",
          instance    = "nadia",
        },
      ]

      job_name        = "static-hosts"
      scrape_interval = "60s"
      metrics_path    = "/metrics"

      forward_to = [prometheus.remote_write.mimir.receiver]
    }
