# Source: csi-drivers
apiVersion: csi.ceph.io/v1
kind: Driver
metadata:
  name: rook-ceph.cephfs.csi.ceph.com
  namespace: rook-ceph
spec:
  log:
    verbosity: 0
    rotation:
      maxFiles: 7
      maxLogSize: 10Gi
      periodicity: daily
  enableFencing: false
  grpcTimeout: 30
  snapshotPolicy: volumeSnapshot
  generateOMapInfo: false
  fsGroupPolicy: None
  attachRequired: true
  deployCsiAddons: false
  cephFsClientType: kernel
  kernelMountOptions: {}
  fuseMountOptions: {}
  nodePlugin:
    serviceAccountName: rook-ceph-cephfs-csi-ceph-com-nodeplugin-sa
    tolerations: []
    imagePullPolicy: IfNotPresent
    volumes: []
  controllerPlugin:
    serviceAccountName: rook-ceph-cephfs-csi-ceph-com-ctrlplugin-sa
    hostNetwork: false
    replicas: 1
    privileged: false
    tolerations: []
    volumes: []
