# Source: surrealdb
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.6.5
  namespace: surrealdb
  annotations:
    noa.re/deploy-id: 7648f36f7dfd32e6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
