# Source: surrealdb
apiVersion: v1
kind: ServiceAccount
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.3.7
