# Source: surrealdb
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.3.7
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
