# Source: relcoord.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: relcoord-noa-re-config
  namespace: relcoord
data:
  relcoord.toml: |-
    host = "0.0.0.0"
    port = 8080

    [persistence]
    uri = "ws://surrealdb.surrealdb.svc:8000"
    namespace = "default"
    database = "relcoord"
    idmouse = {
        url = "http://idmouse.idmouse.svc/token/relcoord",
        token_path = "/var/run/secrets/tokens/idmouse"
    }
    n
