# Source: relcoord.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relcoord-noa-re
  labels:
    app: relcoord-noa-re
  namespace: relcoord
  annotations:
    noa.re/deploy-id: 7058264e90a3666e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relcoord-noa-re
  template:
    metadata:
      labels:
        app: relcoord-noa-re
      annotations:
        checksum/config: 053131f47350952c1e84907f3cf4c778b89d2a32b1a399f2107802ef142ca32e
    spec:
      containers:
      - name: relcoord-noa-re
        image: repo.noa.re/relcoord:0.1.0-af2f5310
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: relcoord-noa-re-config
          mountPath: /config
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: relcoord-noa-re-config
        configMap:
          name: relcoord-noa-re-config
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: idmouse
              expirationSeconds: 3600
              audience: idmouse
          - serviceAccountToken:
              path: idcat.noa.re
              expirationSeconds: 3600
              audience: idcat.noa.re
