# Source: idcat.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: idcat-noa-re-config
  namespace: idcat
data:
  idcat.toml: |
    bind-address = "0.0.0.0:8080"
    private-key-directory = "/app-keys"

    [[identity-provider]]
    name = "kubernetes"
    audience = "idcat.noa.re"
    issuer = "https://kubernetes.default.svc"

    [[identity-provider]]
    name = "buildkite"
    audience = "idcat.noa.re"
    issuer = "https://agent.buildkite.com"

    [[github-app]]
    name = "nresare-buildsystem"
    app-id = 3511383
    secret-key = "nresare-buildsystem.key"

    [[access-policy]]
    identity-provider = "buildkite"
    github-app = "nresare-buildsystem"
    required-claims = {organization_slug="nresare", pipeline_slug="berries-config"}

    [[access-policy]]
    identity-provider = "kubernetes"
    github-app = "nresare-buildsystem"
    required-claims = {sub="system:serviceaccount:default:default"}

    [[access-policy]]
    identity-provider = "kubernetes"
    github-app = "nresare-buildsystem"
    required-claims = {sub="system:serviceaccount:relcoord:default"}
