# Source: idcat.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idcat-noa-re
  labels:
    app: idcat-noa-re
  namespace: idcat
  annotations:
    noa.re/deploy-id: 438cef2feb46eb30
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idcat-noa-re
  template:
    metadata:
      labels:
        app: idcat-noa-re
      annotations:
        checksum/config: de13b7bdd5d534084f3ccb1811d0e423a6e4c64be54f9f4a867c44083d5f2865
    spec:
      containers:
      - name: idcat-noa-re
        image: repo.noa.re/idcat:0.2.1-5f7a206e
        args:
        - --debug
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: idcat-noa-re-config
          mountPath: /config
        - name: app-keys
          mountPath: /app-keys
      volumes:
      - name: idcat-noa-re-config
        configMap:
          name: idcat-noa-re-config
      - name: app-keys
        secret:
          secretName: app-keys
