# Source: mimir
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-ruler
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: ruler
    app.kubernetes.io/version: 3.1.2
  namespace: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: ruler
  maxUnavailable: 1
