# Source: mimir
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/version: 3.1.2
  namespace: mimir
