# Source: grafana-operator
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  annotations:
    noa.re/deploy-id: a953a15bb20ed54e
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  service:
    metadata:
      labels:
        noa.re/discover: enabled
      annotations:
        teleport.dev/name: grafana
  config:
    security:
      csrf_trusted_origins: grafana.teleport.noa.re
    server:
      root_url: https://grafana.teleport.noa.re
