# Source: teleport-kube-agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport-kube-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport-kube-agent
subjects:
- kind: ServiceAccount
  name: teleport-kube-agent
  namespace: teleport
