# Source: trust-manager
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: v0.24.0
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: 'true'
  name: trust-manager-cluster-view
  annotations:
    noa.re/deploy-id: 9e3c05fb973dbc9b
rules:
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles
  verbs:
  - get
  - list
  - watch
