# Source: nack
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstream-controller-cluster-role-binding
  labels:
    app: nack
    chart: nack-0.34.1_noa.1
  annotations:
    noa.re/deploy-id: b6e8423573e89147
subjects:
- kind: ServiceAccount
  name: jetstream-controller
  namespace: nats
roleRef:
  kind: ClusterRole
  name: jetstream-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
