# Source: rook
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceph-csi-metrics-reader
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.0.4
  annotations:
    noa.re/deploy-id: d3e30562295f8ee9
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
