# Source: loki
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.6
  name: loki-clusterrole
  annotations:
    noa.re/deploy-id: 395ac7bbfd02acd0
rules: []
