# Source: idmouse
apiVersion: v1
kind: ConfigMap
metadata:
  name: idmouse-config
  namespace: idmouse
data:
  idmouse.toml: |
    bind_address = "0.0.0.0:8080"
    origin = "http://idmouse.idmouse.svc"

    [authentication]
    audience = "idmouse"
    issuer = "https://kubernetes.default.svc"

    [[mapping]]
    name = "idelephant"
    allowed_subjects = ["system:serviceaccount:idelephant:idelephant"]
    [[mappnig.additional_claims]]
    ns = "default"
    db = "idelephant"
    sub = "idelephant"
    ac = "token_name"
    id = "idelephant"

    [[mapping]]
    name = "some_other_mapping"
    allowed_subjects = ["system:serviceaccount:default:default"]
    additional_claims = { ns = "ns_name", db = "foo" }
