# Source: idmouse
apiVersion: v1
kind: ConfigMap
metadata:
  name: idmouse-config
  namespace: idmouse
data:
  idmouse.toml: |
    bind_address = "0.0.0.0:8080"
    origin = "http://idmouse.idmouse.svc"

    [authentication]
    audience = "idmouse"
    issuer = "https://kubernetes.default.svc"

    [[mapping]]
    name = "idelephant"
    allowed_subjects = ["system:serviceaccount:idelephant:idelephant", "system:serviceaccount:idelephant:default"]
    [mapping.additional_claims]
    ns = "default"
    db = "idelephant"
    ac = "idelephant"
    rl = ["Editor"]
