# Source: idmouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmouse
  labels:
    app: idmouse
  namespace: idmouse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idmouse
  template:
    metadata:
      labels:
        app: idmouse
      annotations:
        checksum/config: 32429625f9ea47e5677313ed4e014c6c6ff9e67fc6c97902a439b962743a37be
    spec:
      serviceAccountName: idmouse
      containers:
      - name: idmouse
        image: nresare/idmouse:latest
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: idmouse-config
          mountPath: /config
      volumes:
      - name: idmouse-config
        configMap:
          name: idmouse-config
