# Source: idmouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmouse
  labels:
    app: idmouse
  namespace: idmouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idmouse
  template:
    metadata:
      labels:
        app: idmouse
      annotations:
        checksum/config: c65f559615d12255d4a6024e7ccfd93073f4e7d75e777d50e96c5f27bf7937ae
    spec:
      containers:
      - name: idmouse
        securityContext:
          allowPrivilegeEscalation: false
        image: packages.buildkite.com/nresare/idmouse/idmouse:0.2.1-9003cca4
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: idmouse-config
          mountPath: /config
      volumes:
      - name: idmouse-config
        configMap:
          name: idmouse-config
