# Source: idmouse
apiVersion: v1
kind: Service
metadata:
  name: idmouse
  namespace: idmouse
spec:
  type: ClusterIP
  selector:
    app: idmouse
  ports:
  - name: http
    port: 80
    targetPort: http
