# Source: id.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-noa-re
  labels:
    app: id-noa-re
  namespace: idelephant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-noa-re
  template:
    metadata:
      labels:
        app: id-noa-re
      annotations:
        checksum/config: 7f52e7374cde436aa379218fcf0ee9aa1ebe0defbacf9d01a4dba10a4f1af1a3
    spec:
      containers:
      - name: id-noa-re
        image: packages.buildkite.com/nresare/idelephant/idelephant:v0.2.3-rc.24-gfcc6c51
        args:
        - -c
        - /config/idelephant.toml
        volumeMounts:
        - name: id-noa-re-config
          mountPath: /config
        - name: db-password
          mountPath: /db-password
        - name: email-password
          mountPath: /email-password
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: id-noa-re-config
        configMap:
          name: id-noa-re-config
      - name: db-password
        secret:
          secretName: db-password
      - name: email-password
        secret:
          secretName: email-password
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: idmouse
              expirationSeconds: 3600
              audience: idmouse
