# Source: webhook-poker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-poker
  labels:
    app: webhook-poker
  namespace: webhook-poker
  annotations:
    noa.re/deploy-id: 726e40d5a1733e4c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-poker
  template:
    metadata:
      labels:
        app: webhook-poker
      annotations:
        checksum/config: 416f7a7b88860f76ac934d5b5529fe8092c1714616202774f015c5b005577922
    spec:
      serviceAccountName: webhook-poker
      containers:
      - name: webhook-poker
        image: public.ecr.aws/portswigger-platform/webhook-poker:0.0.6
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: webhook-poker-config
          mountPath: /config
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: webhook-poker-config
        configMap:
          name: webhook-poker-config
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: nats
              expirationSeconds: 3600
              audience: nats
