# Source: webhook-poker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-poker
  labels:
    app: webhook-poker
  namespace: webhook-poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-poker
  template:
    metadata:
      labels:
        app: webhook-poker
      annotations:
        checksum/config: a4bf222cebd367e23b92cc6f86bd4a6c8a12e2a9cb0b4ccac105f18912a82246
    spec:
      containers:
      - name: webhook-poker
        image: public.ecr.aws/portswigger-platform/webhook-poker:0.0.6
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: webhook-poker-config
          mountPath: /config
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
      volumes:
      - name: webhook-poker-config
        configMap:
          name: webhook-poker-config
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: nats
              expirationSeconds: 3600
              audience: nats
