# Source: webhook-poker
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-poker
  annotations:
    nats.io/allowed-pub-subjects: $JS.API.CONSUMER.INFO.github-events.argo-poker,$JS.API.CONSUMER.MSG.NEXT.github-events.argo-poker,$JS.ACK.github-events.argo-poker.>
    noa.re/deploy-id: 52621872f9e65fcd
  namespace: webhook-poker
