# Source: argo
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/instance: argo
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.4
data:
  applicationsetcontroller.enable.leader.election: 'false'
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  commitserver.log.format: text
  commitserver.log.level: info
  controller.log.format: text
  controller.log.level: info
  dexserver.log.format: text
  dexserver.log.level: info
  notificationscontroller.log.format: text
  notificationscontroller.log.level: info
  redis.server: argo-argocd-redis:6379
  repo.server: argo-argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  server.dex.server: https://argo-argocd-dex-server:5556
  server.dex.server.strict.tls: 'false'
  server.insecure: 'true'
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: 'false'
