# Source: argocd
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.5.1
  annotations:
    noa.re/deploy-id: f65d1aa5953727df
type: Opaque
