# Source: teleport-cluster
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/component: proxy
    app.kubernetes.io/version: 18.2.2
    teleport.dev/majorVersion: '18'
spec:
  secretName: teleport-tls
  dnsNames:
  - teleport.noa.re
  - '*.teleport.noa.re'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
