# Source: teleport-cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleport-cluster-proxy
  namespace: teleport-cluster
  labels:
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/component: proxy
    app.kubernetes.io/version: 18.2.2
    teleport.dev/majorVersion: '18'
automountServiceAccountToken: false
