# Source: acme-dns
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-dns
  namespace: acme-dns
  annotations:
    noa.re/deploy-id: 6f2b339c9ccd2b66
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
