# Source: acme-dns
apiVersion: v1
kind: Service
metadata:
  name: acme-dns
  namespace: acme-dns
spec:
  type: NodePort
  selector:
    app: acme-dns
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
