# Source: teleport-kube-agent
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teleport-kube-agent
  namespace: teleport
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teleport-kube-agent
subjects:
- kind: ServiceAccount
  name: teleport-kube-agent
  namespace: teleport
