# Source: cert-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook:dynamic-serving
  namespace: cert-manager
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: webhook
    app.kubernetes.io/version: v1.18.2
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - cert-manager-webhook-ca
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
