# Source: cert-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-tokenrequest
  namespace: cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v1.18.2
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  resourceNames:
  - cert-manager
  verbs:
  - create
