# Source: envoy-gateway
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: envoy-gateway
    app.kubernetes.io/version: v1.7.0
