# Source: envoy-gateway
apiVersion: v1
kind: Service
metadata:
  name: unifi-noa-re
  namespace: envoy-gateway-system
  annotations:
    noa.re/deploy-id: bbd400b3e174d203
spec:
  ports:
  - name: https
    protocol: TCP
    appProtocol: kubernetes.io/wss
    port: 443
    targetPort: 11443
