# Source: zq.lu
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: zq-lu
  namespace: web
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: zq-lu
    sectionName: https
  validation:
    caCertificateRefs:
    - group: ''
      kind: ConfigMap
      name: cluster-local-ca
    hostname: zq-lu.web.svc
