# Source: zq.lu
apiVersion: v1
kind: Service
metadata:
  name: zq-lu
  namespace: web
spec:
  selector:
    app: zq-lu
  ports:
  - name: https
    appProtocol: https
    protocol: TCP
    port: 443
    targetPort: https
